elk:
    image: mozillapayments/elk
    ports:
      - "5601:5601"
      - "9200:9200"
    expose:
      - "5000"
    volumes:
      - /var/lib/elasticsearch

logstash:
  image: mozillapayments/logstash
  volumes:
    - ../payments-env/data/logs:/data/logs
  links:
    - elk
